safe:        false
port:        4000
baseurl:     /
url:         http://chadmetcalf.github.io
source:      .
destination: ./public
plugins_dir: ./_plugins
future:      true
markdown:    kramdown
permalink:   date
exclude:     ["Gemfile", "Gemfile.lock", "CNAME", "Rakefile", "README.md",
              "public", "Guardfile", "Guardfile", ".DS_Store"]
